# This is a sample of a game set in YAML format.
title: '滑行遊戲 - 基礎關卡'
stages:
  - level: 0
    title: '請使用上下左右鍵移動球，按 r 重來。'
    board: |
      ######
      #S...#
      #....#
      #...E#
      ######
  - level: 1
    title: '有一點點障礙物呢。'
    board: |
      ######
      #S..##
      #....#
      #.#.E#
      ######
  - level: 2
    title: '就算出口浮在中間…'
    board: |
      ########
      #S....##
      #.##...#
      #...E..#
      #......#
      ########
  - level: 3
    title: '每一個金幣得五分！'
    board: |
      ########
      #......#
      #..S...#
      #...E..#
      #..#$..#
      ########
  - level: 4
    title: '你能夠在過關前吃到所有金幣嗎？'
    board: |
      #########
      #...$...#
      #..$.$..#
      #.S....##
      #..$.$..#
      #E..$...#
      #########
  - level: 5
    title: '紅色叉叉是陷阱，踩到會一直扣分，要小心。'
    board: |
      ############
      #..........#
      #..........#
      #.S...t#...#
      #.t........#
      #.#.E......#
      #..........#
      ############